### ISSUE TITLE
what is the license of em-sockify 0.3.2?

### ISSUE THREAD

**Issue by luisapace** [igrigorik/em-socksify#23]
Hi, the em-sockify 0.3.2 at https://github.com/igrigorik/em-socksify/blob/v0.3.2/MIT-LICENSE specifies MIT in the title, but the text in that file is a BSD. 

What is the license: MIT or BSD?

Thanks.

**Comment by luisapace** [comment]
Hi, any news on my question?

**Comment by igrigorik** [comment]
Oops, thanks for flagging this. Per https://github.com/igrigorik/em-socksify/blob/v0.3.2/em-socksify.gemspec#L14, it's supposed to be MIT. That file is unnecessary and I'll remove it.

**Comment by igrigorik** [comment]
Closed via https://github.com/igrigorik/em-socksify/commit/f3bd0bbaf55ad5bd79aab205e8c15d5174a02dbe
